StartupEvents.registry('block', event => {
    event.create('kubejs:copper_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/copper_support")
    event.create('kubejs:bismuth_bronze_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/bismuth_bronze_support")
    event.create('kubejs:black_bronze_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/black_bronze_support")
    event.create('kubejs:bronze_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/bronze_support")
    event.create('kubejs:wrought_iron_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/wrought_iron_support")
    event.create('kubejs:steel_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/steel_support")
    event.create('kubejs:black_steel_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/black_steel_support")
    event.create('kubejs:red_steel_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/red_steel_support")
    event.create('kubejs:blue_steel_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/blue_steel_support")
    event.create('kubejs:galvanized_steel_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/galvanized_steel_support")
    event.create('kubejs:pig_iron_support', 'tfc:support')
        .tagBlock('minecraft:mineable/pickaxe')
        .model("kubejs:block/pig_iron_support")
})
