ServerEvents.recipes(event => {
    const recipedid = 'kubejs:wash_ore/heatore/';
    const { tfc, create } = event.recipes;
    wash_ore.forEach(ore => {


        if (ore.type == '/type_') {
            if (ore.mod == 'tfc_ie_addon:ore') {
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc_ie_addon:ore/small_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 2 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc_ie_addon:ore/poor_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 3 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc_ie_addon:ore/normal_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 5 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc_ie_addon:ore/rich_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 7 } })

                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc_ie_addon:ore/rich_${ore.ore}` }], "results": [{ "count": 7, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 3, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.2, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc_ie_addon:ore/normal_${ore.ore}` }], "results": [{ "count": 7, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 3, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc_ie_addon:ore/poor_${ore.ore}` }], "results": [{ "count": 3, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 1, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc_ie_addon:ore/small_${ore.ore}` }], "results": [{ "count": 2, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.15, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc_ie_addon:ore/small_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 3 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc_ie_addon:ore/poor_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 5 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc_ie_addon:ore/normal_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 8 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc_ie_addon:ore/rich_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 10 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })

            }
            if (ore.mod == 'firmalife:ore') {
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `firmalife:ore/small_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 2 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `firmalife:ore/poor_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 3 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `firmalife:ore/normal_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 5 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `firmalife:ore/rich_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 7 } })
               
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `firmalife:ore/rich_${ore.ore}` }], "results": [{ "count": 7, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 3, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.2, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `firmalife:ore/normal_${ore.ore}` }], "results": [{ "count": 7, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 3, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `firmalife:ore/poor_${ore.ore}` }], "results": [{ "count": 3, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 1, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `firmalife:ore/small_${ore.ore}` }], "results": [{ "count": 2, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.15, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })

                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `firmalife:ore/small_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 3 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `firmalife:ore/poor_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 5 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `firmalife:ore/normal_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 8 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `firmalife:ore/rich_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 10 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
            }
            if (ore.mod == 'tfc:ore') {
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc:ore/small_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 2 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc:ore/poor_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 3 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc:ore/normal_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 5 } })
                event.custom({ "type": "tfc:quern", "ingredient": { "item": `tfc:ore/rich_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 7 } })
                
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc:ore/rich_${ore.ore}` }], "results": [{ "count": 7, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 3, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.2, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc:ore/normal_${ore.ore}` }], "results": [{ "count": 7, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 3, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc:ore/poor_${ore.ore}` }], "results": [{ "count": 3, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.3, "count": 2, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "count": 1, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })
                event.custom({ "type": "create:crushing", "ingredients": [{ "item": `tfc:ore/small_${ore.ore}` }], "results": [{ "count": 2, "item": `kubejs:item/ore/dirty_dust/${ore.ore}` }, { "chance": 0.15, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }, { "chance": 0.15, "item": `kubejs:item/ore/dirty_pile/${ore.ore}` }], "processingTime": 400 })

                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc:ore/small_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 3 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc:ore/poor_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 5 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc:ore/normal_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 8 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })
                event.custom({ "type": "immersiveengineering:crusher", "input": { "item": `tfc:ore/rich_${ore.ore}` }, "result": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}`, "count": 10 }, "secondaries": [{ "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }, { "chance": 0.5, "output": { "item": `kubejs:item/ore/dirty_dust/${ore.ore}` } }], "energy": 2500 })

            }
        }
    })
})