ServerEvents.commandRegistry(event => {
    const { commands: Commands, arguments: Arguments } = event;

    event.register(
        Commands.literal('foodrule')
            .then(Commands.argument('entity', Arguments.ENTITY.create(event))
                .then(Commands.argument('foodKill', Arguments.BOOLEAN.create(event))
                    .executes(context => {
                        let entity = Arguments.ENTITY.getResult(context, 'entity');
                        let needFood = Arguments.BOOLEAN.getResult(context, 'foodKill');

                        if (!entity.isPlayer()) {
                            player.server.tell('§c目标必须是一个玩家！');
                            return 0;
                        }

                        let player = entity;

                        if (needFood == true) {
                            player.server.tell(`已开启素食主义者模式`);
                            player.persistentData.foodKill = true;
                            return 1;
                        }

                        if (needFood == false) {
                            player.server.tell(`已关闭素食主义者模式`);

                            player.persistentData.foodKill = false;

                            return 1;
                        }
                    })
                )
            )
    );
});
const foodKillList = [
    //在这个List加入吃完后会死亡的食物
    "minecraft:cooked_beef",
    "farmersdelight:dog_food",
    "farmersdelight:horse_feed",
    "firmalife:food/bacon",
    "brewinandchewin:quiche_slice",
    "brewinandchewin:quiche",
    "brewinandchewin:scarlet_pierogi",
    "butcher:cookedstomach",
    "butcher:stomach",
    "butcher:kidney",
    "butcher:endermanmeat",
    "butcher:cookedendermanmeat",
    "butcher:suspiciousmeat",
    "alexsmobs:kangaroo_meat",
    "alexsmobs:cooked_kangaroo_meat",
    "butcher:cookedcatmeat",
    "butcher:rawstridermeat",
    "butcher:cookedstridermeat",
    "butcher:rawevokermeat",
    "butcher:cookedevokermeat",
    "butcher:rawguardianmeat",
    "butcher:cookedguardianmeat",
    "butcher:shulkermeat",
    "butcher:cookedshulkermeat",
    "butcher:rawcatmeat",
    "butcher:cookedlungs",
    "butcher:lungs",
    "butcher:cookedintestines",
    "butcher:intestines",
    "alexscaves:slam",
    "alexscaves:cooked_dinosaur_chop",
    "alexscaves:dinosaur_chop",
    "alexscaves:dinosaur_nugget",
    "born_in_chaos_v1:smoked_flesh",
    "butcher:liver",
    "butcher:cookedliver",
    "butcher:cookedkidney",
    "butcher:cookedbloodsausage",
    "butcher:bloodsausage",
    "born_in_chaos_v1:smoked_monster_flesh",
    "born_in_chaos_v1:monster_flesh",
    "butcher:endermankidney",
    "butcher:cookedendermanlungs",
    "butcher:endermanlungs",
    "butcher:endermanheart",
    "butcher:cavespiderleg",
    "farmersdelight:shepherds_pie",
    "farmersdelight:shepherds_pie_block",
    "farmersdelight:honey_glazed_ham",
    "farmersdelight:honey_glazed_ham_block",
    "farmersdelight:roasted_mutton_chops",
    "farmersdelight:grilled_salmon",
    "farm_and_charm:potato_with_roast_meat",
    "farm_and_charm:chicken_wrapped_in_bacon",
    "farm_and_charm:beef_patty_with_vegetables",
    "brewinandchewin:jerky",
    "farmersdelight:cod_slice",
    "farmersdelight:cooked_mutton_chops",
    "farmersdelight:mutton_chops",
    "alexsmobs:kangaroo_burger",
    "kubejs:iceland_mutton",
    "kubejs:rotten_meat",
    "butcher:cookedsausages",
    "butcher:spiderleg",
    "farmersdelight:barbecue_stick",
    "farmersdelight:cooked_salmon_slice",
    "farmersdelight:salmon_slice",
    "farmersdelight:cooked_cod_slice",
    "farmersdelight:cooked_bacon",
    "farmersdelight:bacon",
    "butcher:cookedspiderleg",
    "butcher:heart",
    "butcher:sausages",
    "butcher:cookedendermanliver",
    "butcher:endermanstomach",
    "butcher:cookedendermanstomach",
    "farmersdelight:ham",
    "farmersdelight:cod_roll",
    "farmersdelight:baked_cod_stew",
    "farmersdelight:noodle_soup",
    "farmersdelight:bacon_and_eggs",
    "farmersdelight:pasta_with_mutton_chop",
    "tfc:food/rainbow_trout",
    "tfc:food/largemouth_bass",
    "tfc:food/lake_trout",
    "tfc:food/crappie",
    "tfc:food/bluegill",
    "tfc:food/shellfish",
    "farmersdelight:salmon_roll",
    "farmersdelight:stuffed_potato",
    "farmersdelight:squid_ink_pasta",
    "butcher:endermanintestines",
    "butcher:cookedendermankidney",
    "farmersdelight:smoked_ham",
    "tfc:food/frog_legs",
    "tfc:food/tropical_fish",
    "tfc:food/cooked_salmon",
    "tfc:food/salmon",
    "tfc:food/cooked_cod",
    "tfc:food/cod",
    "firmalife:food/nachos",
    "firmalife:food/cooked_lasagna",
    "butcher:cookedendermanintestines",
    "farmersdelight:stuffed_pumpkin_block",
    "farmersdelight:stuffed_pumpkin",
    "farmersdelight:roast_chicken_block",
    "farmersdelight:roast_chicken",
    "firmalife:food/raw_lasagna",
    "butcher:endermanliver",
    "firmalife:food/burrito",
    "firmalife:food/taco",
    "firmalife:food/cooked_pizza",
    "firmalife:food/maki_roll",
    "firmalife:food/futo_maki_roll",
    "tfc:food/cooked_bluegill",
    "tfc:food/cooked_crappie",
    "tfc:food/cooked_lake_trout",
    "tfc:food/cooked_largemouth_bass",
    "tfc:food/cooked_rainbow_trout",
    "tfc:food/cooked_smallmouth_bass",
    "tfc:food/smallmouth_bass",
    "tfc:food/cooked_frog_legs",
    "tfc:food/cooked_shellfish",
    "brewinandchewin:kippers",
    "brewery:sausage",
    "brewery:half_chicken",
    "firmalife:food/cooked_bacon",
    "farmersdelight:beef_stew",
    "farmersdelight:chicken_soup",
    "farmersdelight:fish_stew",
    "farmersdelight:pasta_with_meatballs",
    "refurbished_furniture:raw_meatlovers_pizza",
    "refurbished_furniture:cooked_meatlovers_pizza",
    "refurbished_furniture:meatlovers_pizza_slice",
    "tfc:food/beef",
    "tfc:food/pork",
    "tfc:food/cooked_duck",
    "tfc:food/cooked_hyena",
    "tfc:food/horse_meat",
    "farmersdelight:mutton_wrap",
    "farmersdelight:minced_beef",
    "minecraft:rabbit_stew",
    "minecraft:rotten_flesh",
    "tfc:food/duck",
    "tfc:food/hyena",
    "tfc:food/bear",
    "tfc:food/chicken",
    "tfc:food/cooked_chicken",
    "tfc:food/rabbit",
    "tfc:food/cooked_rabbit",
    "tfc:food/quail",
    "farmersdelight:chicken_sandwich",
    "farmersdelight:cooked_chicken_cuts",
    "farmersdelight:chicken_cuts",
    "farmersdelight:beef_patty",
    "tfc:food/fox",
    "tfc:food/wolf",
    "tfc:food/venison",
    "tfc:food/peafowl",
    "tfc:food/turkey",
    "tfc:food/cooked_mutton",
    "tfc:food/mutton",
    "tfc:food/cooked_pork",
    "tfc:food/cooked_pheasant",
    "tfc:food/cooked_turkey",
    "tfc:food/cooked_peafowl",
    "tfc:food/cooked_grouse",
    "tfc:food/cooked_venison",
    "tfc:food/cooked_wolf",
    "tfc:food/cooked_fox",
    "tfc:food/pheasant",
    "tfc:food/grouse",
    "butcher:cookedmincedlamb",
    "butcher:pandameat",
    "butcher:rawdolphinmeat",
    "butcher:dolphinmeat",
    "butcher:mincedbeef",
    "butcher:cookedmincebeef",
    "butcher:pork_shoulder",
    "brewery:fried_chicken",
    "butcher:raw_pork_belly",
    "butcher:lamb_shoulder",
    "tfc:food/cooked_horse_meat",
    "tfc:food/cooked_bear",
    "tfc:food/cooked_quail",
    "tfc:food/cooked_beef",
    "tfc:food/calamari",
    "tfc:food/camelidae",
    "tfc:food/turtle",
    "tfc:food/gran_feline",
    "tfc:food/chevon",
    "butcher:pork_belly",
    "tfc:food/cooked_turtle",
    "tfc:food/cooked_calamari",
    "tfc:food/protein_soup",
    "tfc:food/protein_salad",
    "tfc:food/cooked_gran_feline",
    "tfc:food/cooked_camelidae",
    "tfc:food/cooked_chevon",
    "butcher:lamb_loin",
    "butcher:pork_leg",
    "butcher:rawdragonmeat",
    "butcher:mincedlamb",
    "butcher:cooked_orange_frog_leg",
    "butcher:batmeat",
    "butcher:cookedbatmeat",
    "butcher:rawpandameat",
    "butcher:raw_pork_shoulder",
    "butcher:cookedpillagermeat",
    "butcher:humanflesh",
    "butcher:humanmeat",
    "butcher:cooked_dragon_meat",
    "butcher:creepermeat",
    "butcher:pillagermeat",
    "butcher:cookedgoldaxolotlmeat",
    "butcher:cookedcyanaxolotlmeat",
    "butcher:cookedblueexolotlmeat",
    "butcher:rawwitchmeat",
    "butcher:witchmeat",
    "butcher:cookedhumanmeat",
    "butcher:villager_meat",
    "butcher:cooked_villager_meat",
    "butcher:hoglinmeat",
    "butcher:sniffermeat",
    "butcher:cookedocelotmeat",
    "butcher:scraps",
    "butcher:frogsleg",
    "butcher:cooked_green_frogs_leg",
    "butcher:gray_frog_leg",
    "butcher:cooked_gray_frog_leg",
    "butcher:rawcreepermeat",
    "butcher:elder_meat",
    "butcher:raweldermeat",
    "butcher:raw_lamb_shoulder",
    "butcher:rawlambloin",
    "butcher:raw_pork_leg",
    "butcher:rawocelotmeat",
    "butcher:rawwildaxolotlmeat",
    "butcher:rawlucyaxolotlmeat",
    "butcher:rawgoldaxolotlmeat",
    "butcher:rawcyanaxolotlmeat",
    "butcher:rawblueaxolotlmeat",
    "butcher:cookedwildaxolotlmeat",
    "butcher:cookedlucyaxolotlmeat",
    "butcher:cookedsniffermeat",
    "butcher:orange_frog_leg",
    "butcher:cookedhoglinmeat"
]
ItemEvents.foodEaten(event => {
    const { player, server, item } = event
    if (foodKillList.indexOf(item.id) != -1) {
        if (player.persistentData.foodKill) {
            damagePlayer(server, player, 'kubejs:carnivorous', 1234567)
            // 在zh_ch "death.attack.carnivorous":"%1$s 死于肉食"
        }
    }
})