ServerEvents.tags('item', event => {
     event.add('ad_astra:held_over_head', 'siegemachines:mortar')       // 大炮
     event.add('ad_astra:held_over_head', 'siegemachines:culverin')
     event.add('ad_astra:held_over_head', 'siegemachines:catapult')
     event.add('ad_astra:held_over_head', 'siegemachines:catapult')
     event.add('ad_astra:held_over_head', 'siegemachines:trebuchet')
     event.add('ad_astra:held_over_head', 'siegemachines:ballista')
     event.add('ad_astra:held_over_head', 'siegemachines:battering_ram')
     event.add('ad_astra:held_over_head', 'siegemachines:siege_ladder')
     event.add('ad_astra:held_over_head', 'trotting_wagons:armored_wagon')
     event.add('ad_astra:held_over_head', 'trotting_wagons:conestoga_wagon')
     event.add('ad_astra:held_over_head', 'trotting_wagons:royal_wagon')
     event.add('tfc:prospectable', 'tfc:kaolin_clay_grassr')
     event.add('tfc:prospectable', 'tfc:white_kaolin_clay')
     event.add('tfc:prospectable', 'tfc:pink_kaolin_clay')
     event.add('tfc:prospectable', 'tfc:pink_kaolin_clay')
})