// for 1.18 pls use: onEvent("morejs.villager.trades", (event) => { ... })
MoreJSEvents.wandererTrades((event) => {
    const trade = 
    //金币>>摸彩袋
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 8, 16)], Item.of('afc:wood/barrel/cypress', '{BlockEntityTag:{id:"tfc:barrel",inventory:{inventory:{Items:[],Size:3},tank:{Amount:4000,FluidName:"tfc:whiskey"}}}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 8, 16)], Item.of('afc:wood/barrel/cypress', '{BlockEntityTag:{id:"tfc:barrel",inventory:{inventory:{Items:[],Size:3},tank:{Amount:4000,FluidName:"tfc:beer"}}}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 8, 16)], Item.of('afc:wood/barrel/cypress', '{BlockEntityTag:{id:"tfc:barrel",inventory:{inventory:{Items:[],Size:3},tank:{Amount:4000,FluidName:"artisanal:schmaltz"}}}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 8, 16)], Item.of('afc:wood/barrel/cypress', '{BlockEntityTag:{id:"tfc:barrel",inventory:{inventory:{Items:[],Size:3},tank:{Amount:4000,FluidName:"tfc:olive_oil"}}}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('afc:wood/barrel/cypress', '{BlockEntityTag:{id:"tfc:barrel",inventory:{inventory:{Items:[],Size:3},tank:{Amount:4000,FluidName:"minecraft:milk"}}}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 10, 15)], Item.of('waterflasks:leather_flask', '{Damage:0,Fluid:{Amount:500,FluidName:"firmalife:goat_milk"}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 10, 15)], Item.of('waterflasks:leather_flask', '{Damage:0,Fluid:{Amount:500,FluidName:"firmalife:mead"}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 10, 15)], Item.of('waterflasks:leather_flask', '{Damage:0,Fluid:{Amount:500,FluidName:"minecraft:milk"}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 10, 15)], Item.of('waterflasks:leather_flask', '{Damage:0,Fluid:{Amount:500,FluidName:"artisanal:apple_juice"}}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,id:"tfc:seeds/rye"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/maize_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/rice_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/wheat_flour"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,id:"tfc:seeds/oat"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/oat_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/barley_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/rye_flour"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,id:"tfc:seeds/oat"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/oat_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/barley_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/rye_flour"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/oat_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/rye_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/rye_grain"},{Count:8b,id:"tfc:seeds/wheat"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/barley_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/wheat_grain"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/barley_grain"},{Count:8b,id:"tfc:seeds/maize"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/rice_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/maize_flour"},{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33048000L,traits:[]}},id:"tfc:food/oat_grain"},{Count:8b,id:"tfc:seeds/rice"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33186000L,traits:[]}},id:"tfc:food/squash"},{Count:8b,id:"tfc:seeds/beet"},{Count:8b,id:"tfc:seeds/jute"},{Count:8b,id:"tfc:seeds/tomato"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33186000L,traits:[]}},id:"tfc:food/soybean"},{Count:8b,id:"tfc:seeds/green_bean"},{Count:8b,id:"tfc:seeds/potato"},{Count:8b,id:"tfc:seeds/sugarcane"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33186000L,traits:[]}},id:"tfc:food/green_bean"},{Count:8b,id:"tfc:seeds/carrot"},{Count:8b,id:"tfc:seeds/papyrus"},{Count:8b,id:"tfc:seeds/onion"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 10, 18)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:food":{creationDate:33186000L,traits:[]}},id:"firmalife:food/fig"},{Count:8b,id:"tfc:seeds/soybean"},{Count:8b,id:"tfc:seeds/cabbage"},{Count:8b,id:"tfc:seeds/garlic"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 7, 13)], Item.of('minecraft:bundle', '{Items:[{Count:8b,id:"tfc:rock/loose/basalt"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:ore/normal_cassiterite"},{Count:8b,id:"tfc:powder/wood_ash"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:powder/garnierite"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 7, 13)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:ore/poor_magnetite"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:powder/magnetite"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:powder/tetrahedrite"},{Count:8b,id:"tfc:rock/loose/basalt"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 7, 13)], Item.of('minecraft:bundle', '{Items:[{Count:8b,id:"tfc:powder/amethyst"},{Count:8b,id:"tfc:rock/loose/gneiss"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:powder/native_copper"},{Count:8b,id:"tfc:powder/sylvite"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 7, 13)], Item.of('minecraft:bundle', '{Items:[{Count:4b,ForgeCaps:{"tfc:food":{creationDate:33228000L,traits:[]}},id:"artisanal:perishable_sugar"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:ore/poor_hematite"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:powder/hematite"},{Count:8b,id:"tfc:rock/loose/chert"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 7, 13)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:kaolin_clay"},{Count:8b,id:"tfc:rock/loose/granite"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:ore/cryolite"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:powder/garnierite"}]}')) 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3), TradeItem.of("kubejs:crown", 7, 13)], Item.of('minecraft:bundle', '{Items:[{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:ore/normal_native_silver"},{Count:8b,id:"tfc:rock/loose/chalk"},{Count:8b,ForgeCaps:{"tfc:item_heat":{heat:0.0f,ticks:0L}},id:"tfc:powder/magnetite"},{Count:8b,id:"tfc:powder/graphite"}]}')) 
    .maxUses(1)
    //金币>>农作物/零散种子
    event.addTrade(1, [TradeItem.of("kubejs:crown", 4, 8)], TradeItem.of("tfc:food/barley", 8, 12)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 4, 8)], TradeItem.of("tfc:food/maize", 8, 12)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 4, 8)], TradeItem.of("tfc:food/oat", 8, 12)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 4, 8)], TradeItem.of("tfc:food/rye", 8, 12)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 4, 8)], TradeItem.of("tfc:food/rice", 8, 12)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 4, 8)], TradeItem.of("tfc:food/wheat", 8, 12)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 10)], TradeItem.of("tfc:food/onion", 5, 9)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 10)], TradeItem.of("tfc:food/carrot", 5, 9)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 12)], TradeItem.of("tfc:food/potato", 7, 11)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 10)], TradeItem.of("tfc:food/tomato", 5, 9)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 10)], TradeItem.of("tfc:food/cabbage", 5, 9)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 10)], TradeItem.of("tfc:food/beet", 5, 9)) 
    .maxUses(4)
    //金币>>植物
    event.addTrade(1, [TradeItem.of("kubejs:crown", 9, 14)], TradeItem.of("firmalife:plant/fig_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 9, 15)], TradeItem.of("firmalife:plant/cocoa_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 11)], TradeItem.of("tfc:plant/orange_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 11)], TradeItem.of("tfc:plant/cherry_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 11)], TradeItem.of("tfc:plant/plum_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 11)], TradeItem.of("tfc:plant/red_apple_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 11)], TradeItem.of("tfc:plant/banana_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 13)], TradeItem.of("tfc:plant/olive_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 11)], TradeItem.of("tfc:plant/lemon_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 11)], TradeItem.of("tfc:plant/green_apple_sapling", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 16)], TradeItem.of("tfc:plant/blueberry_bush", 2, 4)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 16)], TradeItem.of("tfc:plant/raspberry_bush", 2, 4)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 16)], TradeItem.of("tfc:plant/elderberry_bush", 2, 4)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 16)], TradeItem.of("tfc:plant/blackberry_bush", 2, 4)) 
    .maxUses(4)
    //金币>>面包
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:food/barley_bread", 4, 8))
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:food/maize_bread", 4, 8))
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:food/oat_bread", 4, 8))
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:food/rye_bread", 4, 8))
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:food/rice_bread", 4, 8))
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:food/wheat_bread", 4, 8))
    .maxUses(4)
    //金币>>奶酪
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 15)], TradeItem.of("firmalife:food/cheddar", 2, 4)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 15)], TradeItem.of("firmalife:food/chevre", 2, 4)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 15)], TradeItem.of("firmalife:food/rajya_metok", 2, 4)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 15)], TradeItem.of("firmalife:food/gouda", 2, 4)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 15)], TradeItem.of("firmalife:food/feta", 2, 4)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 15)], TradeItem.of("firmalife:food/shosha", 2, 4)) 
    .maxUses(3)
    //金币>>干燥食物
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 14)], TradeItem.of("brewinandchewin:jerky", 6, 10)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 14)], TradeItem.of("brewinandchewin:kippers", 6, 12)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 14)], TradeItem.of("brewinandchewin:pickled_pickles", 6, 12)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], TradeItem.of("farmersdelight:smoked_ham", 2, 4)) 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 14)], TradeItem.of("firmalife:food/hardtack", 5, 9)) 
    .maxUses(2)
    //金币>>酒水
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 10)], "vinery:mead") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 10)], "vinery:strad_wine") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 10)], "vinery:eiswein") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 7, 12)], "vinery:apple_cider") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 14)], "vinery:cristel_wine") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 10)], "vinery:glowing_wine") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 9)], TradeItem.of("brewinandchewin:bloody_mary", 2, 4)) 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 9)], TradeItem.of("brewinandchewin:egg_grog", 2, 4)) 
    .maxUses(2)
    //金币>>皮革
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], TradeItem.of("textile:black_bear_fur", 1, 2)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], TradeItem.of("textile:caribou_fur", 1, 2)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], TradeItem.of("textile:tiger_fur", 1, 2)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], TradeItem.of("textile:crocodile_leather", 1, 2)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], TradeItem.of("textile:direwolf_fur", 1, 2)) 
    .maxUses(3)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], TradeItem.of("minecraft:leather", 2, 4)) 
    .maxUses(4)
    //金币>>杂项
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 16)], "kubejs:bronze_lockpick") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 14)], "kubejs:bronze_simple_key") 
    .maxUses(2)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 8, 14)], TradeItem.of("legendarysurvivaloverhaul:bandage", 1, 3)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 5, 13)], "kubejs:healing_paste") 
    .maxUses(3)
    event.addTrade(1, ["tfc:powder/sapphire", TradeItem.of("kubejs:crown", 10, 16)], TradeItem.of("legendarysurvivaloverhaul:ice_fern_leaf", 2, 4)) 
    .maxUses(4)
    event.addTrade(1, ["tfc:powder/ruby", TradeItem.of("kubejs:crown", 10, 16)], TradeItem.of("legendarysurvivaloverhaul:sun_fern_leaf", 2, 4)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 12, 20)], "firmaciv:nav_clock") 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 14)], "immersive_melodies:lute") 
    .maxUses(1)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 10, 16)], TradeItem.of("tfc:ore/rich_native_gold", 1, 2)) 
    .maxUses(4)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("minecraft:clay", 7, 14)) 
    .maxUses(6)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:kaolin_clay", 5, 8)) 
    .maxUses(6)
    event.addTrade(1, [TradeItem.of("kubejs:crown", 6, 12)], TradeItem.of("tfc:red_kaolin_clay", 5, 8)) 
    .maxUses(6)
    event.addTrade(1, [TradeItem.of("kubejs:leather_plate", 4, 7)], TradeItem.of("kubejs:crown", 8, 14)) 
    .maxUses(6)
    event.addTrade(1, [TradeItem.of("kubejs:silver_fragments", 4, 8)], TradeItem.of("kubejs:crown", 10, 16)) 
    .maxUses(6)
    event.addTrade(1, [TradeItem.of("kubejs:leather_scrap", 3, 6)], TradeItem.of("kubejs:crown", 9, 15)) 
    .maxUses(6)


    //特殊>>宝石>>金币
    event.addTrade(2, [TradeItem.of("tfc:gem/emerald", 2, 5)], TradeItem.of("kubejs:crown", 12, 20)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/sapphire", 2, 5)], TradeItem.of("kubejs:crown", 12, 20)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/ruby", 2, 5)], TradeItem.of("kubejs:crown", 14, 24)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/opal", 2, 5)], TradeItem.of("kubejs:crown", 8, 15)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/lapis_lazuli", 2, 5)], TradeItem.of("kubejs:crown", 10, 15)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/diamond", 2, 5)], TradeItem.of("kubejs:crown", 16, 28)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/amethyst", 2, 5)], TradeItem.of("kubejs:crown", 10, 15)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/topaz", 2, 5)], TradeItem.of("kubejs:crown", 8, 14)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:gem/pyrite", 2, 5)], TradeItem.of("kubejs:crown", 8, 14)) 
    .maxUses(4)
    event.addTrade(2, [TradeItem.of("tfc:ore/rich_native_gold", 1, 3)], TradeItem.of("kubejs:crown", 4, 10)) 
    .maxUses(4)
    //特殊>>宝石>>戒指
    event.addTrade(2, [TradeItem.of("tfc:gem/emerald", 2, 5), TradeItem.of("shiny_ornaments:rose_gold_delicacy_ring", 1, 1)], "shiny_ornaments:rose_gold_emerald_ring") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/opal", 2, 5), TradeItem.of("shiny_ornaments:gold_ring", 1, 1)], "shiny_ornaments:golden_opal_ring") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/sapphire", 2, 5), TradeItem.of("shiny_ornaments:silver_ring", 1, 1)], "shiny_ornaments:silver_sapphire_ring") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/ruby", 2, 5), TradeItem.of("shiny_ornaments:rose_gold_delicacy_ring", 1, 1)], "shiny_ornaments:rose_gold_ruby_ring") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/ruby", 2, 5), TradeItem.of("shiny_ornaments:silver_ring", 1, 1)], "shiny_ornaments:silver_ruby_ring") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/diamond", 2, 5), TradeItem.of("shiny_ornaments:gold_ring", 1, 1)], "shiny_ornaments:golden_diamond_ring") 
    .maxUses(1)
    //特殊>>宝石/金币>>背包
    event.addTrade(2, [TradeItem.of("tfc:gem/emerald", 2, 5), TradeItem.of("kubejs:crown", 12, 20)], "backpacked_tfc:backpack") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:ore/rich_native_gold", 5, 8), TradeItem.of("kubejs:crown", 10, 16)], "backpacked_tfc:backpack") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("kubejs:crown", 24, 36)], "tfccanes:refined_walking_cane") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:metal/sheet/wrought_iron", 1, 1), TradeItem.of("kubejs:crown", 10, 18)], "born_in_chaos_v1:hound_trap") 
    .maxUses(2)
    //特殊>>宝石/金币>>艺术品
    event.addTrade(2, [TradeItem.of("tfc:gem/opal", 1, 1), TradeItem.of("kubejs:crown", 12, 20)], "supplementaries:globe") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/emerald", 1, 1), TradeItem.of("kubejs:crown", 12, 20)], "handcrafted:evoker_trophy") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/emerald", 1, 1), TradeItem.of("kubejs:crown", 12, 20)], "handcrafted:pillager_trophy") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/emerald", 1, 1), TradeItem.of("kubejs:crown", 12, 20)], "handcrafted:vindicator_trophy") 
    .maxUses(1)
    event.addTrade(2, [TradeItem.of("tfc:gem/emerald", 1, 1), TradeItem.of("kubejs:crown", 12, 20)], "handcrafted:witch_trophy") 
    .maxUses(1)
    
}) 