StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:sterling_silver_ruby_ring')
        .texture('kubejs:item/sterling_silver_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:blood_spell_power", "blood_spell_power", 0.05, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 2.5, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:sterling_silver_opal_ring')
        .texture('kubejs:item/sterling_silver_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.05, "multiply_total")
        .modifyAttribute("irons_spellbooks:eldritch_spell_power", "eldritch_spell_power", 0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:sterling_silver_amethyst_ring')
        .texture('kubejs:item/sterling_silver_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", 0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:sterling_silver_diamond_ring')
        .texture('kubejs:item/sterling_silver_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:holy_spell_power", "holy_spell_power", 0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:sterling_silver_pyrite_ring')
        .texture('kubejs:item/sterling_silver_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -2, "addition")
        .modifyAttribute("irons_spellbooks:lightning_spell_power", "lightning_spell_power", 0.15, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:sterling_silver_ender_pearl_ring')
        .texture('kubejs:item/sterling_silver_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("irons_spellbooks:ender_spell_power", "ender_spell_power", 0.2, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:sterling_silver_lapis_ring')
        .texture('kubejs:item/sterling_silver_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 2, "addition")
        .modifyAttribute("irons_spellbooks:ice_magic_resist", "ice_magic_resist", 0.08, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:sterling_silver_topaz_ring')
        .texture('kubejs:item/sterling_silver_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:fire_magic_resist", "fire_magic_resist", 0.09, "multiply_total")
        .modifyAttribute("more_attributes:hunger_consumption", "hunger", -0.05, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:sterling_silver_sapphire_ring')
        .texture('kubejs:item/sterling_silver_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:ice_spell_power", "ice_spell_power", 0.05, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 2.5, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:sterling_silver_emerald_ring')
        .texture('kubejs:item/sterling_silver_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.1, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:sterling_silver_cinnabar_ring')
        .texture('kubejs:item/sterling_silver_cinabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:fire_spell_power", "fire_spell_power", 0.08, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 2, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:sterling_silver_jade_ring')
        .texture('kubejs:item/sterling_silver_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:nature_spell_power", "nature_spell_power", 0.1, "multiply_total")
        )
        .tag("curios:ring")
})