StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:rose_gold_ruby_ring')
        .texture('kubejs:item/rose_gold_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.06, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.10, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 4, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:rose_gold_opal_ring')
        .texture('kubejs:item/rose_gold_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.13, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.05, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:rose_gold_amethyst_ring')
        .texture('kubejs:item/rose_gold_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.08, "multiply_total")
        .modifyAttribute("scguns:bullet_damage_multiplier", "scguns:bullet_damage_multiplier", 0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:rose_gold_diamond_ring')
        .texture('kubejs:item/rose_gold_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:critical_chance", "critical_chance", 0.15, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:rose_gold_pyrite_ring')
        .texture('kubejs:item/rose_gold_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 3, "addition")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 4, "addition")
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 310, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:rose_gold_ender_pearl_ring')
        .texture('kubejs:item/rose_gold_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:rose_gold_lapis_ring')
        .texture('kubejs:item/rose_gold_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 3.5, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:rose_gold_topaz_ring')
        .texture('kubejs:item/rose_gold_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:hunger_consumption", "hunger_consumption", 0.1, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 4, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:rose_gold_sapphire_ring')
        .texture('kubejs:item/rose_gold_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 4, "addition")
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 50, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:rose_gold_emerald_ring')
        .texture('kubejs:item/rose_gold_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.25, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:rose_gold_cinnabar_ring')
        .texture('kubejs:item/rose_gold_cinabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 2, "addition")
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.05, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 3.5,"addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:rose_gold_jade_ring')
        .texture('kubejs:item/rose_gold_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 6, "addition")
        .modifyAttribute("more_attributes:critical_damage", "critical_damage", 0.1, "multiply_total")
        )
        .tag("curios:ring")
})