StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:steel_ruby_ring')
        .texture('kubejs:item/steel_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.04, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.15, "multiply_total")
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", -0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_opal_ring')
        .texture('kubejs:item/steel_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.25, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", -0.15, "multiply_total")
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", -0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_amethyst_ring')
        .texture('kubejs:item/steel_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", -0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_diamond_ring')
        .texture('kubejs:item/steel_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:ranged_damage", "ranged_damage", 0.09, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.09, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -4, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:steel_pyrite_ring')
        .texture('kubejs:item/steel_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 7, "addition")
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", -0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:lightning_magic_resist", "lightning_magic_resist", -0.1, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_ender_pearl_ring')
        .texture('kubejs:item/steel_ender_pearl_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.1, "addition")
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 680, "addition")
        .modifyAttribute("parcool:stamina_recovery", "stamina_recovery", -0.15, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:steel_lapis_ring')
        .texture('kubejs:item/steel_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 5, "addition")
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", -300, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_topaz_ring')
        .texture('kubejs:item/steel_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 450, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.15, "multiply_total")
        .modifyAttribute("more_attributes:hunger_consumption", "hunger_consumption", 0.15, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heating_temperature", "heating_temperature", 8, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_sapphire_ring')
        .texture('kubejs:item/steel_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 100, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", -0.15, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cooling_temperature", "cooling_temperature", -6, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:steel_emerald_ring')
        .texture('kubejs:item/steel_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 8, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", -0.25, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_cinnabar_ring')
        .texture('kubejs:item/steel_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 3,"addition")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 3, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:steel_jade_ring')
        .texture('kubejs:item/steel_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -3, "addition")
        )
        .tag("curios:ring")
})