StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:golden_ruby_ring')
        .texture('kubejs:item/golden_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.12, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 3, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_opal_ring')
        .texture('kubejs:item/golden_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_amethyst_ring')
        .texture('kubejs:item/golden_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.1, "multiply_total")
        .modifyAttribute("more_attributes:ranged_damage", "ranged_damage", 0.05, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_diamond_ring')
        .texture('kubejs:item/golden_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:critical_chance", "critical_chance", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 1, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 2, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:golden_pyrite_ring')
        .texture('kubejs:item/golden_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_knockback", "generic.attack_knockback", 0.25, "multiply_total")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 4, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_ender_pearl_ring')
        .texture('kubejs:item/golden_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 450, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:golden_lapis_ring')
        .texture('kubejs:item/golden_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 5, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_topaz_ring')
        .texture('kubejs:item/golden_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 200, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.05, "multiply_total")
        .modifyAttribute("more_attributes:hunger_consumption", "hunger_consumption", -0.1, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_sapphire_ring')
        .texture('kubejs:item/golden_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 100, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.05, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 4, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:golden_emerald_ring')
        .texture('kubejs:item/golden_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 1, "addition")
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.1, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_cinnabar_ring')
        .texture('kubejs:item/golden_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 3, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 2.5, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:golden_jade_ring')
        .texture('kubejs:item/golden_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 2, "addition")
        .modifyAttribute("more_attributes:critical_damage", "critical_damage", 0.15, "multiply_total")
        )
        .tag("curios:ring")

})