StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:silver_ruby_ring')
        .texture('kubejs:item/silver_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 50, "addition")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.05, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_opal_ring')
        .texture('kubejs:item/silver_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.05, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_amethyst_ring')
        .texture('kubejs:item/silver_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.05, "multiply_total")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 1, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_diamond_ring')
        .texture('kubejs:item/silver_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.1, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:silver_pyrite_ring')
        .texture('kubejs:item/silver_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:pell_power", "spell_power", 0.08, "multiply_total")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 2, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_ender_pearl_ring')
        .texture('kubejs:item/silver_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.25, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:silver_lapis_ring')
        .texture('kubejs:item/silver_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 1, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_topaz_ring')
        .texture('kubejs:item/silver_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 150, "addition")
        .modifyAttribute("more_attributes:hunger_consumption", "hunger", -0.05, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_sapphire_ring')
        .texture('kubejs:item/silver_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 50, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 2, "addition")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:silver_emerald_ring')
        .texture('kubejs:item/silver_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 1, "addition")
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.08, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_cinnabar_ring')
        .texture('kubejs:item/silver_cinabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 2, "addition")
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 25, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:silver_jade_ring')
        .texture('kubejs:item/silver_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:critical_damage", "critical_damage", 0.1, "multiply_total")
        )
        .tag("curios:ring")
})