StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:black_steel_ruby_ring')
        .texture('kubejs:item/black_steel_ruby_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", 0.15, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:heating_temperature", "heating_temperature", 15, "addition")
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", -0.2, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_opal_ring')
        .texture('kubejs:item/black_steel_opal_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.2, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.15, "multiply_total")
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", -0.25, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_amethyst_ring')
        .texture('kubejs:item/black_steel_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.1, "multiply_total")
        .modifyAttribute("more_attributes:ranged_damage", "ranged_damage", 0.15, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_knockback", "generic.attack_knockback", -0.2, "multiply_total")
        .modifyAttribute("minecraft:generic.armor", "generic.armor", -6, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_diamond_ring')
        .texture('kubejs:item/black_steel_diamond_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.15, "multiply_total")
        .modifyAttribute("more_attributes:critical_damage", "critical_damage", 0.2, "multiply_total")
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", -4, "addition")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:black_steel_pyrite_ring')
        .texture('kubejs:item/black_steel_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 6, "addition")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 6, "addition")
        .modifyAttribute("forge:block_reach", "block_reach", -0.25, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", -0.25, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_ender_pearl_ring')
        .texture('kubejs:item/black_steel_ender_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.15, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cooling_temperature", "cooling_temperature", -8,"addition")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", -6, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_lapis_ring')
        .texture('kubejs:item/black_steel_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.5, "addition")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 6, "addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", -0.2, "multiply_total")
        .modifyAttribute("more_attributes:critical_damage", "critical_damage", -0.2, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_topaz_ring')
        .texture('kubejs:item/black_steel_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 640, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.1, "multiply_total")
        .modifyAttribute("more_attributes:hunger_consumption", "hunger_consumption", 0.1, "multiply_total")
        .modifyAttribute("parcool:stamina_recovery", "stamina_recovery", -0.2, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_sapphire_ring')
        .texture('kubejs:item/black_steel_sapphire_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 300, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:cooling_temperature", "cooling_temperature", -10,"addition")
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.15, "multiply_total")
        )
        .tag("curios:ring")

        event
        .create('shiny_ornaments:black_steel_emerald_ring')
        .texture('kubejs:item/black_steel_emerald_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 4, "addition")
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.25, "multiply_total")
        .modifyAttribute("more_attributes:hunger_consumption", "hunger", 0.25, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_cinnabar_ring')
        .texture('kubejs:item/black_steel_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:hunger_consumption", "hunger", -0.5, "multiply_total")
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", -0.15, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_steel_jade_ring')
        .texture('kubejs:item/black_steel_jade_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.1, "multiply_total")
        .modifyAttribute("more_attributes:critical_damage", "critical_damage", 0.35, "multiply_total")
        .modifyAttribute("minecraft:generic.attack_speed", "attack_speed", -0.35, "multiply_total")
        )
        .tag("curios:ring")
})