StartupEvents.registry('item', event => {
    event
        .create('shiny_ornaments:copper_amethyst_ring')
        .texture('kubejs:item/copper_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.03, "multiply_total")
        )
        .tag("curios:ring")
    event
        .create('shiny_ornaments:copper_pyrite_ring')
        .texture('kubejs:item/copper_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 3, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_lapis_ring')
        .texture('kubejs:item/copper_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 2, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_topaz_ring')
        .texture('kubejs:item/copper_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 150, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:copper_cinnabar_ring')
        .texture('kubejs:item/copper_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 2, "addition")
        .modifyAttribute("legendarysurvivaloverhaul:heat_resistance", "heat_resistance", 1, "addition")
        )
        .tag("curios:ring")

        //黑铜合金戒指

        event
        .create('shiny_ornaments:black_bronze_amethyst_ring')
        .texture('kubejs:item/black_bronze_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:cast_time_reduction", "cast_time_reduction", 0.05, "multiply_total")
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_bronze_pyrite_ring')
        .texture('kubejs:item/black_bronze_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:lightning_spell_power", "lightning_spell_power", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_bronze_lapis_ring')
        .texture('kubejs:item/black_bronze_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:ice_spell_power", "ice_spell_power", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_bronze_topaz_ring')
        .texture('kubejs:item/black_bronze_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:black_bronze_cinnabar_ring')
        .texture('kubejs:item/black_bronze_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:fire_spell_power", "fire_spell_power", 0.05, "multiply_total")
        )
        .tag("curios:ring")

        //青铜合金戒指

        event
        .create('shiny_ornaments:bronze_amethyst_ring')
        .texture('kubejs:item/bronze_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:ranged_damage", "ranged_damage", 0.09, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bronze_pyrite_ring')
        .texture('kubejs:item/bronze_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:critical_chance", "critical_chance", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bronze_lapis_ring')
        .texture('kubejs:item/bronze_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 3, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bronze_topaz_ring')
        .texture('kubejs:item/bronze_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:hunger_consumption", "hunger", -0.05, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bronze_cinnabar_ring')
        .texture('kubejs:item/bronze_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.max_health", "generic.max_health", 1, "addition")
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.05, "multiply_total")
        )
        .tag("curios:ring")

        //铋铜合金戒指

        event
        .create('shiny_ornaments:bismuth_bronze_amethyst_ring')
        .texture('kubejs:item/bismuth_bronze_amethyst_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.07, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bismuth_bronze_pyrite_ring')
        .texture('kubejs:item/bismuth_bronze_pyrite_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("betterstealth:stealth", "stealth", 0.1, "multiply_total")
        .modifyAttribute("minecraft:generic.armor_toughness", "armor_toughness", 1, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bismuth_bronze_lapis_ring')
        .texture('kubejs:item/bismuth_bronze_lapis_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("forge:block_reach", "block_reach", 0.25, "addition")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bismuth_bronze_topaz_ring')
        .texture('kubejs:item/bismuth_bronze_topaz_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max",160, "addition")
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event
        .create('shiny_ornaments:bismuth_bronze_cinnabar_ring')
        .texture('kubejs:item/bismuth_bronze_cinnabar_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 2, "addition")
        )
        .tag("curios:ring")
})